name: Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please include context and the problem you’re trying to solve.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you’ve considered
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, references
    validations:
      required: false
